<div class="jumbotron">
    <h1>Welcome to the <span class="zf-green">Onyx User Module</span></h1>
    <p>Congratulations! You have successfully installed the Onyx User Module</p>
    <p><a class="btn btn-success btn-lg" href="/user/login">Login &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Active User</h3>
            </div>
            <div class="panel-body">
                <p><pre><?php var_dump($this->ident); ?></pre></p>
                <p><a class="btn btn-success pull-right" href="/user/logout">Logout &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Onyx User Module</h3>
            </div>
            <div class="panel-body">
                <p>Check out the Onyx Module on <a href="https://github.com/paul-headington/OnyxUser" target="_blank">Github</a></p>
                <p><a class="btn btn-success pull-right" href="https://github.com/paul-headington/OnyxUser" target="_blank">Github &raquo;</a></p>
            </div>
        </div>
    </div>

</div>
