<form class="form-signin" role="form" action="" method="POST" enctype="multipart/form-data">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="email" class="form-control" placeholder="Email address" name="email" id="email" required autofocus>
        <input type="password" class="form-control" placeholder="Password" name="password" id="password" required>
        <label class="checkbox">
          <input type="checkbox" value="remember-me" name="remeber" id="remeber"> Remember me
        </label>
        <div class="form-group">
              <p>Forgot your password? <a href="/user/forgot-password">click here</a></p>
          </div>
          <input type="hidden" name="backto" id="backto" value="<?php echo $this->backto;?>"/>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

<div class="row">    
    <?php 
    if(is_array($this->messages)){         
        $messageBody = '';
        foreach($this->messages as $message){
            $messageBody .= '<p>'.$message.'</p>';
        }          
    ?>
    <div class="col-md-12"><?php echo $messageBody; ?></div>
    <?php }?>   
        
</div>


