<div class="container-fluid">
    <h1 class="avenir-black aqua-font info-heading">LOGIN</h1>
    
    <?php
    if(is_array($this->messages) && count($this->messages) > 0){         
        $messageBody = '';
        foreach($this->messages as $message){
            $messageBody .= $message.'<br/>';
        }          
    ?>
    <div class="row alert alert-error red">
        <div class="col-md-12"><span class="fa fa-times"></span> <?php echo $messageBody; ?></div>
    </div>
    <?php }?>
</div>
 


<form class="form container-fluid" action="/user/login" method="POST" enctype="multipart/form-data">
    <input id="do_not_fill_me_in" class="do_not_fill_me_in is-hidden" type="text" name="do_not_fill_me_in" size="25" value="" />
    <div class="modal-body">
        <div class="row">
            <div class="input-group col-sm-6 col-md-6">
                <span class="input-group-addon login-icon">@</span>
                <input type="text" name="email" id="email" required autofocus class="form-control" placeholder="Email">
            </div>

            <div class="input-group col-sm-6 col-md-6">
                <span class="input-group-addon fa fa-key login-icon"></span>
                <input type="password" class="form-control" placeholder="Password" name="password" id="password" required>
            </div>
        </div>
        <input type="hidden" name="backto" id="backto" value="<?php echo $this->backto;?>"/>
        <div class="row avenir-medium login-error">
            <div class=" col-sm-6 col-md-6 red-font">
                
                
            </div>
             <div class=" col-sm-6 col-md-6">
                 <a class="aqua-font" href="/user/forgot-password">Forgot your password?</a>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <div class="row">
            <div class=" col-sm-6 col-md-6 avenir-roman align-left">
                <input type="checkbox" value="remember-me" name="remeber" id="remeber" /> <label for="remeber">Remember my email</label>
            </div>
            <div class=" col-sm-6 col-md-6 align-right">
                <button class="btn grey-light avenir-medium more-btn login-cancel" data-dismiss="modal">CANCEL</button>
                <input class="btn aqua avenir-medium more-btn login-button" type="submit" value="LOGIN" />
            </div>
        </div>
    </div>
</form>


