<div class="row">
    <?php if($this->success){?>
    <?php if($this->done){?>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Password successfully reset</h3>
            </div>
            <div class="panel-body">
                <p>To access your account please login <a href="/user/login">here</a></p>
            </div>
        </div>
    </div>
    <?php }else{?>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Password reset</h3>
            </div>
            <div class="panel-body">
                <p>To reset your password please enter a new password here</p>
                <form role="form" action="" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                  <label for="password">Password</label>
                  <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" required>
                </div>
                <div class="form-group">
                  <label for="password-repeat">Password repeat</label>
                  <input type="password" class="form-control" id="password-repeat" name="password-repeat" placeholder="Repeat password" required>
                </div>
                <button type="submit" class="btn btn-default">Reset Password</button>
                <p><?php echo $this->message;?></p>
                </form>
            </div>
        </div>
    </div>    
    <?php }?>
    <?php }else{?>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Invalid Token</h3>
            </div>
            <div class="panel-body">
                <p>your reset token is invalid or expired.</p>
            </div>
        </div>
    </div>
    <?php }?>
  
</div>
